name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Build executable
      run: |
        uv run pyinstaller --onefile --name "엑셀통합프로그램" excel_merger.py
        uv run pyinstaller --onedir --windowed --name "엑셀통합프로그램_앱" excel_merger.py
        
    - name: Create release package
      run: |
        cd dist
        # 파일 크기 확인
        ls -la
        # 더 작은 압축 파일 생성
        zip -r ../엑셀통합프로그램_${GITHUB_REF_NAME}.zip 엑셀통합프로그램
        # 앱 번들은 별도로 압축
        zip -r ../엑셀통합프로그램_앱_${GITHUB_REF_NAME}.zip 엑셀통합프로그램_앱.app
        cd ..
        # 파일 크기 확인
        ls -la *.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          엑셀통합프로그램_${{ github.ref_name }}.zip
          엑셀통합프로그램_앱_${{ github.ref_name }}.zip
        body: |
          ## 엑셀 통합 프로그램 v${{ github.ref_name }}
          
          ### 다운로드
          - **단일 실행 파일**: `엑셀통합프로그램_${{ github.ref_name }}.zip` (터미널에서 실행)
          - **macOS 앱**: `엑셀통합프로그램_앱_${{ github.ref_name }}.zip` (더블클릭으로 실행)
          
          ### 사용법
          1. 압축 파일을 다운로드하고 압축 해제
          2. 원하는 실행 파일을 선택하여 실행
          3. 처음 실행 시 "확인되지 않은 개발자" 경고가 나타날 수 있음
          4. 시스템 환경설정 > 보안 및 개인 정보 보호에서 "허용" 클릭
          
          ### 시스템 요구사항
          - macOS 10.15 (Catalina) 이상
          - 최소 4GB RAM
          
          ### 변경사항
          - 초기 릴리즈
          - 쿠팡, 올웨이즈, 토스, 네이버 플랫폼 지원
          - 쌀 및 구운란 상품 처리
          - 포커스 양식 엑셀 파일 생성
        draft: false
        prerelease: false
        permissions: write
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 